version: "3.8"
services:
  flask-app:
    image: davidhei/ssl-automation-app:1.6.3
    container_name: flask-app
    ports:
      - "4000:4000"
    environment:
      - FLASK_ENV=production
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=4000
    restart: always
    volumes:
      - .:/app
    depends_on:
      - certbot
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - ./letsencrypt-site:/var/www/certbot
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do sleep 2073600; done'
    restart: always
