apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssl-automation-app
  labels:
    app: ssl-automation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ssl-automation
  template:
    metadata:
      labels:
        app: ssl-automation
    spec:
      containers:
      - name: ssl-automation-app
        image: davidhei/ssl-automation-app:1.6.0
        ports:
        - containerPort: 4000
        env:
        - name: FLASK_ENV
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: ssl-automation-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 4000
  selector:
    app: ssl-automation
